name: tenicos_nextline
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  generic_bloc_provider: ^1.0.9
  firebase_database: ^4.0.0
  firebase_storage: ^4.0.0
  firebase_core: ^0.5.0
  dio: ^3.0.10
  shared_preferences: ^0.5.8
  sqflite: ^1.3.1
  geolocator: ^6.1.13
  web_socket_channel: ^1.1.0
  flutter_svg: ^0.18.0
  map_launcher: ^0.12.2
  image_picker: ^0.6.7
  basic_utils: ^2.6.0
  photo_view: ^0.10.1
  signature: ^3.2.0
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_launcher_icons: "^0.8.0"
  flutter_test:
    sdk: flutter


flutter_icons:
  image_path: "assets/images/imagotipo.png"
  android: true
  ios: true

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  fonts:
    - family: fontTitle
      fonts:
        - asset: fonts/TrebuchetBold.TTF
    - family: fontSubTitle
      fonts:
        - asset: fonts/TrebuchetRegular.TTF
    - family: fontInput
      fonts:
        - asset: fonts/SegoeUI.ttf
    - family: fontPoppinsBold
      fonts:
        - asset: fonts/PoppinsBold.ttf
    - family: fontPoppinsLight
      fonts:
        - asset: fonts/PoppinsLight.ttf
    - family: fontPoppinsRegular
      fonts:
        - asset: fonts/PoppinsRegular.ttf
    - family: fontPoppinsSemiBold
      fonts:
        - asset: fonts/PoppinsSemiBold.ttf

  assets:
    - assets/images/fondo_login.png
    - assets/images/fondo_home.png
    - assets/images/fondo_app.png
    - assets/images/fondo_top_tickets.png
    - assets/images/imagotipo.png
    - assets/images/info.svg
    - assets/images/plus.svg
    - assets/images/logo_white.svg
    - assets/images/up-arrow.svg
    - assets/images/down-arrow.svg
    - assets/images/bg.jpg
    - assets/images/splash.jpg
    - assets/images/logo_without_text.svg
    - assets/images/icon_download.svg
    - assets/images/logomenu.jpg
    - assets/images/cerrarsesion.svg

